# Concepts and measures

## What is demography anyway, and why should I care?

:::{.rmdimportant}
### Definitions of demography {.unnumbered}
:::

### Okay so what's a "population" then?

### Why is demography important?

## The balancing equation of population change

### Visualizing the balancing equation: Sweden in 1988

:::{.rmdtip}
**DEMOGRAPHY & DATA SCIENCE**

### Balancing equation for customers and employees

#### Customer analytics

#### Employee analytics
:::

## The structure of demographic rates

## Period rates and person-years

## Principal period rates in demography

:::{.rmdtip}
**DEMOGRAPHY & DATA SCIENCE**

### Principal period rates for customers and employees

#### Customer analytics

#### Employee analytics
:::

## Growth rates in demography

### Crude growth rate

### Instantaneous growth rate

### Doubling time

### Comparison of crude growth rate and mean annualized growth rate

:::{.rmdtip}
**DEMOGRAPHY & DATA SCIENCE**

### Customer and employee headcount growth rates

#### Customer analytics

#### Employee analytics
:::

## Estimating period person years

:::{.rmdtip}
**DEMOGRAPHY & DATA SCIENCE**

### The promise (and peril) of knowing exact person years
:::

## The concept of a cohort

:::{.rmdtip}
**DEMOGRAPHY & DATA SCIENCE**

### The use and misuse of the term "cohort" in the corporate world
:::

## Probabilities of occurrence of events

:::{.rmdtip}
**DEMOGRAPHY & DATA SCIENCE**

### Confusion between rates and probabilities in the corporate world
:::
