# Life tables and single decrement processes

:::{.rmdcaution}
<center>
**CAUTION**

The complete version of these notes hasn't been released.
</center>
:::

:::{.rmdimportant}
## Notes for 402 instructor Phil Hurvitz {.unnumbered}

### Lifetables from Humanity Mortality Database (HMD) via `HMDHFDplus` {.unnumbered}

The HMD is back! This week, students will be called upon to use mortality and exposure data from HMD to construct life tables. Luckily, they'll be able to check their work, because HMD also publishes life tables.

Example: fltper_1x1 is the name of the dataset for a female lifetable with one-year age groups for one-year periods 1920-2018.

Recall the [gist I wrote for accessing HMD data](https://github.com/hanowell/uwsoc533a/blob/main/gists/HMDHFDplus-gist.R). This week, to acquire both mortality and life table data, students would need to know about HMD item codes with the following naming convention:

[one-letter sex code]ltper_[length of age interval in years]_[length of period in years]

One-letter sex codes:

* b: Both male and female
* f: Female
* m: Male

I will show them what each of the columns in these tables mean. All you need to do is show them how they can access the lifetable data using `HMDHFDplus`.

### Death counts and population sizes from HMD {.unnumbered}

In addition to lifetables datasets, students will be using death counts and annual population estimates. HMD uses the following definitions that students should be familiar with:

**Deaths**: Death counts are collected at the finest level of detail available. If raw data are aggregated, uniform methods are used to estimate death counts by completed age (i.e., age-last-birthday at time of death), calendar year of death, and calendar year of birth. Death datasets have the following naming convention:

Deaths_[length of age interval in years]_[length of period in years]

**Population size**: Estimates of the population exposed to the risk of death during some age-time interval are based on annual (January 1st) population estimates, with a small correction that reflects the timing of deaths within the interval. Death datasets have the following naming convention:

* "Population" is for population estimates in 1-year age intervals for 1-year periods
* "Population5" is for population estimates in 5-year age intervals for 1-year periods

### Easy lifetable construction using `demogR` {.unnumbered}

The `demogR::life.table` function allows for the construction of lifetables from enumerated deaths and mid-year population counts. I will illustrate manual lifetable construction using the `demogR::goodman` dataset using methods from the [Using rules of thumb] section, checking it against the results of `demogR::life.table` under two settings:

* When `type = "kf"` in `demogR::life.table`, the Keyfitz-Flieger method cited in [Graduation of the age-specific mortality rate (${}_{n}m_x$) function] is used for estimating ${}_{n}a_{x}$.
* When `type = "cd"` instead, the Coale-Demeny method discussed in [The very young ages] is used instead.

The `demogR` manual provides a good worked example of constructed a life table from the enumerated deaths and mid-year population estimates in the `goodman` dataset:

```{r eval=FALSE, include=FALSE}
data(goodman)
## default type="kf"
vlt <- with(goodman, life.table(x=age, nKx=ven.nKx, nDx=ven.nDx))
## compare nax values for cd vs kf life tables
vlt1 <- with(goodman, life.table(x=age, nKx=ven.nKx, nDx=ven.nDx, type="cd"))
vlt$nax[1:2]
vlt1$nax[1:2]
## now construct a cohort life table for Himalayan thar,
## (Hemitargus jemlahicus)
data(thar)
thar.lt <- with(thar, life.table(x=age, nDx=deaths, nKx=count,
type="cohort", iwidth=1, width12=c(1,1)))
thar.lt
```

Closer to week 4, I will provide a helpful gist for you. Until then, I hope these notes help you get familiar with the package.

### `demography`: An alternative package for lifetable construction

The `demography::lifetable` function also produces an easy lifetable, although unfortunately the package isn't well documented in terms of which methods it uses for period lifetable construction and I haven't had time to dig into the function to figure out what it uses. In any case, the RPubs page shows how to use the function: https://rpubs.com/Timexpo/487053. See the sections titled "Example Zero" and "Example One."

### Using `flextable` and `DT` to print life table output

Students will find it useful to learn how to take a lifetable (whether one they build using `demogR` or `demography`, or one they extract from HMD) and display it in a beautiful data table using either the `flextable` or `DT`. Since you're already teaching how to build tables in R in week 3 (same week as my lifetables course), perhaps you could use a lifetable example.
:::

## Period life tables

## Strategies for making age-specific rate $\rightarrow$ probability (${}_{n}m_x$ $\rightarrow$ ${}_{n}q_x$) conversion

### Direction observation (duh)

:::{.rmdtip}
**DEMOGRAPHY & DATA SCIENCE**

#### Direct observation is almost almost possible in the corporate world

#### But not always...
:::

### Graduation of the age-specific mortality rate (${}_{n}m_x$) function

### Borrowing average person-years lived (${}_{n}a_x$) values from another population

### Using rules of thumb

## The very young ages

## The open-ended age interval

## Review of the steps for period life table construction

## Interpreting the life table

## The life table conceived as a stationary population

## Mortality as a continuous process

## Life table construction revisited

## Decomposing a difference in life expectancies

## Adaptation of the life table for studying other single decrement processes

:::{.rmdtip}
**DEMOGRAPHY & DATA SCIENCE**

### Beware of the all-cause attrition hegemon
:::
