# Stable population model

:::{.rmdcaution}
<center>
**CAUTION**

These notes are under construction.
</center>
:::

## First, some review! {.unnumbered}

<details>
<summary>What are the characteristics of a **stationary population**? **Tap for answer**</summary>

1. Constant births per time period
1. Age-specific mortality rates constant over time
1. Net zero migration at all ages

</details>

<details>
<summary>What are the key consequences of these characteristics? **Tap for answer**</summary>

1. Constant age-specific population sizes
1. Thus constant age structure
1. And constant population size

</details>

<details>
<summary>What are some ways we can relax the stationary population model assumptions? **Tap for answer**</summary>

1. Births growing or shrink at constant rate (This week)
1. Fertility rate varies by age (Also this week)
1. Positive or negative net migration (Also this week, kinda)
1. Age-specific vital rates change over time (Chapter 8)

</details>

## A simplified example of a stable population

## Lotka's demonstration of conditions producing a stable population

## The equations characterizing a stable population

## The "stable equivalent" population

## The relation between the instrinsic growth rate and the net reproductive rate

## The effects of fertility and mortality changes age structure, growth rates, birth rates, and death rates

### Effect of fertility changes

### Effect of mortality changes

## The momentum of population growth

## Uses of the stable population model in demographic estimation
